[package]
name = "mio_channel"
version = "0.1.0"
edition = "2021"
description = "Provide a wrapper of the standard channel that can be polled with Mio."
authors = ["ohjinsu@codersproduct.com"]
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mio = { version = "0.8.5", features = ["os-poll", "net"] }
